function getDataLaura() {
    return [
        {
            id: 1,
            title: 'Thailand',
            description: 'Thailand offers the perfect holiday balance for any visitor. You will meet friendly people and visit ancient temples.',
            coverImg: '/public/coverImages/thailand.png',
            price: 1400,
            vat: 294,
            discountedPrice: 1300,
            quantity: 5,
            customer: {
                name: 'Boris Johnson',
                street: '10 Downing Street',
                city: 'London',
                zip: 'SW1A2A',
                country: 'United Kingdom',
            },
            status: 'pending',
        },

        {
            id: 2,
            title: 'Vietnam',
            description: 'Vietnam is fast becoming the destination in demand when travellers visit Asia.',
            coverImg: '/public/coverImages/vietnam.png',
            price: 1500,
            vat: 394,
            discountedPrice: 1370,
            quantity: 2,
            customer: {
                name: 'John Appleseed',
                street: '7 Apple Street',
                city: 'New York',
                zip: '524758',
                country: 'USA',
            },
            status: 'completed',
        },

        {
            id: 3,
            title: 'Australia',
            description: 'Australia is the sixth-largest landmass in the world, supporting endless diversity across territories.',
            coverImg: '/public/coverImages/Australia.png',
            price: 2000,
            vat: 420,
            discountedPrice: 1980,
            quantity: 3,
            customer: {
                name: 'Very Peri',
                street: '77 Blossomville',
                city: 'Barcelona',
                zip: '894874',
                country: 'Kingdom',
            },
            status: 'cancelled',
        },

        {
            id: 4,
            title: 'Brazil',
            description: 'Brazil is the largest country in South and Central America and the fifth largest in the world.',
            coverImg: '/public/coverImages/Brasil.png',
            price: 2500,
            vat: 550,
            discountedPrice: 2100,
            quantity: 4,
            customer: {
                name: 'Lyric Byrd',
                street: '8 Applegate Road',
                city: 'Mountain View',
                zip: '07054',
                country: 'Australia',
            },
            status: 'completed',
        },

        {
            id: 5,
            title: 'Laos',
            description: 'Laos is a landlocked nation located in the middle of the Southeast Asian peninsula.',
            coverImg: '/public/coverImages/Laos.png',
            price: 1400,
            vat: 280,
            discountedPrice: 1100,
            quantity: 2,
            customer: {
                name: 'Sloane Huang',
                street: '85 Lafayette Drive',
                city: 'San Francisco',
                zip: '32303',
                country: 'Spain',
            },
            status: 'pending',
        },

        {
            id: 6,
            title: 'Cambodia',
            description: 'Cambodia is a safe place to travel independently. It is easy to meet other like-minded travellers along the way.',
            coverImg: '/public/coverImages/Cambodia.png',
            price: 1600,
            vat: 320,
            discountedPrice: 1400,
            quantity: 4,
            customer: {
                name: 'Jaslyn Shaffer',
                street: '62 Cemetery Lane',
                city: 'Barcelona',
                zip: '54115',
                country: 'Spain',
            },
            status: 'pending',
        },

        {
            id: 7,
            title: 'China',
            description: 'China, being the 4th largest country in area in the World and the 4th most visited country by foreigners.',
            coverImg: '/public/coverImages/China.png',
            price: 2550,
            vat: 310,
            discountedPrice: 2140,
            quantity: 2,
            customer: {
                name: 'Mekhi Curtis',
                street: '766 E. Depot Ave.',
                city: 'Malden',
                zip: '02148',
                country: 'Italy',
            },
            status: 'completed',
        },

        {
            id: 8,
            title: 'Canada',
            description: 'Spend one night in Toronto, Canada largest city and air hub, before flying to Resolute.',
            coverImg: '/public/coverImages/Canada.png',
            price: 3600,
            vat: 720,
            discountedPrice: 3190,
            quantity: 6,
            customer: {
                name: 'Ellie Cain',
                street: '14 Cobblestone St.',
                city: 'West Bloomfield',
                zip: '48322',
                country: 'France',
            },
            status: 'cancelled',
        },

        {
            id: 9,
            title: 'Iceland',
            description: 'Iceland is home to some incredible natural scenery. A relatively young, geographically isolated country.',
            coverImg: '/public/coverImages/Iceland.png',
            price: 3600,
            vat: 720,
            discountedPrice: 3190,
            quantity: 6,
            customer: {
                name: 'Ellie Cain',
                street: '7527 West Holly St.',
                city: 'Fort Wayned',
                zip: '12445',
                country: 'India',
            },
            status: 'completed',
        },

        {
            id: 10,
            title: 'India',
            description: 'India is blessed with a tropical climate for the majority of the year, loose-fitting are recommended.',
            coverImg: '/public/coverImages/India.png',
            price: 2200,
            vat: 440,
            discountedPrice: 1970,
            quantity: 1,
            customer: {
                name: 'Litzy Chen',
                street: '8233 N. Edgewood Street',
                city: 'Faribault',
                zip: '55021',
                country: 'Portugal',
            },
            status: 'pending',
        },

        {
            id: 11,
            title: 'Japan',
            description: 'Japan is a volcanic archipelago consisting of 6,852 islands. The largest are Honshu, Hokkaido, Kyushu, and Shikoku.',
            coverImg: '/public/coverImages/Japan.png',
            price: 2200,
            vat: 440,
            discountedPrice: 1970,
            quantity: 3,
            customer: {
                name: 'Ellie Cain',
                street: '257 Schoolhouse Rd.',
                city: 'Torrington',
                zip: '06790',
                country: 'Monaco',
            },
            status: 'cancelled',
        },

        {
            id: 12,
            title: 'Kenya',
            description: 'Kenya as synonymous with wildlife (and to some, perhaps marathon runners) and rightly so.',
            coverImg: '/public/coverImages/Kenya.png',
            price: 3000,
            vat: 600,
            discountedPrice: 2860,
            quantity: 4,
            customer: {
                name: 'Ruben Vaughn',
                street: '367 Smith Store Drive',
                city: 'Danville',
                zip: '24540',
                country: 'Panama',
            },
            status: 'completed',
        },

        {
            id: 13,
            title: 'Tanzania',
            description: 'A major city in Tanzania with easy access to the most popular safari parks is Arusha in the north east.',
            coverImg: '/public/coverImages/Tanzania.png',
            price: 2400,
            vat: 480,
            discountedPrice: 2130,
            quantity: 2,
            customer: {
                name: 'Blaze Flores',
                street: '424 Fawn Drive',
                city: 'Oak Forest',
                zip: '60452',
                country: 'Ireland',
            },
            status: 'pending',
        },

        {
            id: 14,
            title: 'Tanzania',
            description: 'Stroll along the timbered walkways and beneath the colonial-style buildings',
            coverImg: '/public/coverImages/Maldives.png',
            price: 3600,
            vat: 720,
            discountedPrice: 3180,
            quantity: 2,
            customer: {
                name: 'Holly May',
                street: '466 Longfellow St.',
                city: 'Soddy Daisy',
                zip: '37379',
                country: 'Mexico',
            },
            status: 'completed',
        },

        {
            id: 15,
            title: 'Mauritius',
            description: 'The best time to travel to Mauritius is between the months of May and December, this is when the weather is dry.',
            coverImg: '/public/coverImages/Mauritius.png',
            price: 2000,
            vat: 200,
            discountedPrice: 1970,
            quantity: 5,
            customer: {
                name: 'Roderick Cuevas',
                street: '5 Harrison St.',
                city: 'Wenatchee',
                zip: '98801',
                country: 'Egypt',
            },
            status: 'cancelled',
        },

        {
            id: 16,
            title: 'New Zealand',
            description: 'New Zealand is truly a year-round destination. It has moderate weather patterns that allow you to enjoy outdoor activities.',
            coverImg: '/public/coverImages/New_Zealand.png',
            price: 5000,
            vat: 1000,
            discountedPrice: 4670,
            quantity: 2,
            customer: {
                name: 'Arturo Owens',
                street: '367 Smith Store Drive',
                city: 'Danville',
                zip: '24540',
                country: 'Turkey',
            },
            status: 'pending',
        },

        {
            id: 17,
            title: 'Peru',
            description: 'Backed by some of the richest cultures ever recorded, The Moche, Nazca, Tiahuanaco, Wari, Chimu and of course the Incas Peru',
            coverImg: '/public/coverImages/Peru.png',
            price: 4800,
            vat: 960,
            discountedPrice: 4230,
            quantity: 6,
            customer: {
                name: 'Adeline Stevens',
                street: '424 Fawn Drive',
                city: 'Oak Forest',
                zip: '60452',
                country: 'Greece',
            },
            status: 'completed',
        },

        {
            id: 18,
            title: 'Srilanka',
            description: 'Sri Lanka is a beautiful island country in the Indian Ocean, about 32 kilometres off the south east coast of India.',
            coverImg: '/public/coverImages/srilanka.png',
            price: 1460,
            vat: 292,
            discountedPrice: 1250,
            quantity: 2,
            customer: {
                name: 'Bryan Hanson',
                street: '466 Longfellow St.',
                city: 'Soddy Daisy',
                zip: '37379',
                country: 'Malta',
            },
            status: 'pending',
        },

        {
            id: 19,
            title: 'USA',
            description: 'Head on a tropical getaway to the islands of Hawaii to explore the dramatic history of Honolulu.',
            coverImg: '/public/coverImages/USA.png',
            price: 4800,
            vat: 960,
            discountedPrice: 3200,
            quantity: 4,
            customer: {
                name: 'Porter Aguirre',
                street: '5 Harrison St.',
                city: 'Wenatchee',
                zip: '98801',
                country: 'Luxembourg',
            },
            status: 'completed',
        },

        {
            id: 20,
            title: 'India',
            description: 'The Golden Triangle is a great introduction to India, especially if time is limited.',
            coverImg: '/public/coverImages/India.png',
            price: 1300,
            vat: 260,
            discountedPrice: 1100,
            quantity: 5,
            customer: {
                name: 'Trinity Zamora',
                street: '9712 Kirkland Drive',
                city: 'Raeford',
                zip: '28376',
                country: 'Sweden',
            },
            status: 'completed',
        },
    ]
}

export default getDataLaura