function getDataLaura() {
    return [
        {
            id: 1,
            title: 'Thailand',
            description: 'Thailand offers the perfect holiday balance for any visitor. You will meet friendly people and visit ancient temples.',
            coverImg: '/coverImages/thailand.png',
            price: 1400,
            vat: 294,
            discountedPrice: 1300,
            quantity: 5,
            customerName: 'Boris Johnson',
            customerStreet: '10 Downing Street',
            customerCity: 'London',
            customerZIP: 'SW1A2A',
            customerCountry: 'United Kingdom',
            status: 'pending',
        },

        {
            id: 2,
            title: 'Vietnam',
            description: 'Vietnam is fast becoming the destination in demand when travellers visit Asia.',
            coverImg: '/coverImages/vietnam.png',
            price: 1500,
            vat: 394,
            discountedPrice: 1370,
            quantity: 2,
            customerName: 'John Appleseed',
            customerStreet: '7 Apple customerStreet',
            customerCity: 'New York',
            customerZIP: '524758',
            customerCountry: 'USA',
            status: 'completed',
        },

        {
            id: 3,
            title: 'Australia',
            description: 'Australia is the sixth-largest landmass in the world, supporting endless diversity across territories.',
            coverImg: '/coverImages/Australia.png',
            price: 2000,
            vat: 420,
            discountedPrice: 1980,
            quantity: 3,
            customerName: 'Very Peri',
            customerStreet: '77 Blossomville',
            customerCity: 'Barcelona',
            customerZIP: '894874',
            customerCountry: 'Kingdom',
            status: 'cancelled',
        },

        {
            id: 4,
            title: 'Brazil',
            description: 'Brazil is the largest country in South and Central America and the fifth largest in the world.',
            coverImg: '/coverImages/Brasil.png',
            price: 2500,
            vat: 550,
            discountedPrice: 2100,
            quantity: 4,
            customerName: 'Lyric Byrd',
            customerStreet: '8 Applegate Road',
            customerCity: 'Mountain View',
            customerZIP: '07054',
            customerCountry: 'Australia',
            status: 'completed',
        },

        {
            id: 5,
            title: 'Laos',
            description: 'Laos is a landlocked nation located in the middle of the Southeast Asian peninsula.',
            coverImg: '/coverImages/Laos.png',
            price: 1400,
            vat: 280,
            discountedPrice: 1100,
            quantity: 2,
            customerName: 'Sloane Huang',
            customerStreet: '85 Lafayette Drive',
            customerCity: 'San Francisco',
            customerZIP: '32303',
            customerCountry: 'Spain',
            status: 'pending',
        },

        {
            id: 6,
            title: 'Cambodia',
            description: 'Cambodia is a safe place to travel independently. It is easy to meet other like-minded travellers along the way.',
            coverImg: '/coverImages/Cambodia.png',
            price: 1600,
            vat: 320,
            discountedPrice: 1400,
            quantity: 4,
            customerName: 'Jaslyn Shaffer',
            customerStreet: '62 Cemetery Lane',
            customerCity: 'Barcelona',
            customerZIP: '54115',
             customerCountry: 'Spain',
            status: 'pending',
        },

        {
            id: 7,
            title: 'China',
            description: 'China, being the 4th largest country in area in the World and the 4th most visited country by foreigners.',
            coverImg: '/coverImages/China.png',
            price: 2550,
            vat: 310,
            discountedPrice: 2140,
            quantity: 2,
            customerName: 'Mekhi Curtis',
            customerStreet: '766 E. Depot Ave.',
            customerCity: 'Malden',
            customerZIP: '02148',
            customerCountry: 'Italy',
            status: 'completed',
        },

        {
            id: 8,
            title: 'Canada',
            description: 'Spend one night in Toronto, Canada largest customerCity and air hub, before flying to Resolute.',
            coverImg: '/coverImages/Canada.png',
            price: 3600,
            vat: 720,
            discountedPrice: 3190,
            quantity: 6,
            customerName: 'Ellie Cain',
            customerStreet: '14 Cobblestone St.',
            customerCity: 'West Bloomfield',
            customerZIP: '48322',
            customerCountry: 'France',
            status: 'cancelled',
        },

        {
            id: 9,
            title: 'Iceland',
            description: 'Iceland is home to some incredible natural scenery. A relatively young, geographically isolated country.',
            coverImg: '/coverImages/Iceland.png',
            price: 3600,
            vat: 720,
            discountedPrice: 3190,
            quantity: 6,
            customerName: 'Ellie Cain',
            customerStreet: '7527 West Holly St.',
            customerCity: 'Fort Wayned',
            customerZIP: '12445',
            customerCountry: 'India',
            status: 'completed',
        },

        {
            id: 10,
            title: 'India',
            description: 'India is blessed with a tropical climate for the majority of the year, loose-fitting are recommended.',
            coverImg: '/coverImages/India.png',
            price: 2200,
            vat: 440,
            discountedPrice: 1970,
            quantity: 1,
            customerName: 'Litzy Chen',
            customerStreet: '8233 N. Edgewood customerStreet',
            customerCity: 'Faribault',
            customerZIP: '55021',
            customerCountry: 'Portugal',
            status: 'pending',
        },

        {
            id: 11,
            title: 'Japan',
            description: 'Japan is a volcanic archipelago consisting of 6,852 islands. The largest are Honshu, Hokkaido, Kyushu, and Shikoku.',
            coverImg: '/coverImages/Japan.png',
            price: 2200,
            vat: 440,
            discountedPrice: 1970,
            quantity: 3,
            customerName: 'Ellie Cain',
            customerStreet: '257 Schoolhouse Rd.',
            customerCity: 'Torrington',
            customerZIP: '06790',
            customerCountry: 'Monaco',
            status: 'cancelled',
        },

        {
            id: 12,
            title: 'Kenya',
            description: 'Kenya as synonymous with wildlife (and to some, perhaps marathon runners) and rightly so.',
            coverImg: '/coverImages/Kenya.png',
            price: 3000,
            vat: 600,
            discountedPrice: 2860,
            quantity: 4,
            customerName: 'Ruben Vaughn',
            customerStreet: '367 Smith Store Drive',
            customerCity: 'Danville',
            customerZIP: '24540',
            customerCountry: 'Panama',
            status: 'completed',
        },

        {
            id: 13,
            title: 'Tanzania',
            description: 'A major customerCity in Tanzania with easy access to the most popular safari parks is Arusha in the north east.',
            coverImg: '/coverImages/Tanzania.png',
            price: 2400,
            vat: 480,
            discountedPrice: 2130,
            quantity: 2,
            customerName: 'Blaze Flores',
            customerStreet: '424 Fawn Drive',
            customerCity: 'Oak Forest',
            customerZIP: '60452',
            customerCountry: 'Ireland',
            status: 'pending',
        },

        {
            id: 14,
            title: 'Tanzania',
            description: 'Stroll along the timbered walkways and beneath the colonial-style buildings',
            coverImg: '/coverImages/Maldives.png',
            price: 3600,
            vat: 720,
            discountedPrice: 3180,
            quantity: 2,
            customerName: 'Holly May',
            customerStreet: '466 Longfellow St.',
            customerCity: 'Soddy Daisy',
            customerZIP: '37379',
            customerCountry: 'Mexico',
            status: 'completed',
        },

        {
            id: 15,
            title: 'Mauritius',
            description: 'The best time to travel to Mauritius is between the months of May and December, this is when the weather is dry.',
            coverImg: '/coverImages/Mauritius.png',
            price: 2000,
            vat: 200,
            discountedPrice: 1970,
            quantity: 5,
            customerName: 'Roderick Cuevas',
            customerStreet: '5 Harrison St.',
            customerCity: 'Wenatchee',
            customerZIP: '98801',
            customerCountry: 'Egypt',
            status: 'cancelled',
        },

        {
            id: 16,
            title: 'New Zealand',
            description: 'New Zealand is truly a year-round destination. It has moderate weather patterns that allow you to enjoy outdoor activities.',
            coverImg: '/coverImages/New_Zealand.png',
            price: 5000,
            vat: 1000,
            discountedPrice: 4670,
            quantity: 2,
            customerName: 'Arturo Owens',
            customerStreet: '367 Smith Store Drive',
            customerCity: 'Danville',
            customerZIP: '24540',
            customerCountry: 'Turkey',
            status: 'pending',
        },

        {
            id: 17,
            title: 'Peru',
            description: 'Backed by some of the richest cultures ever recorded, The Moche, Nazca, Tiahuanaco, Wari, Chimu and of course the Incas Peru',
            coverImg: '/coverImages/Peru.png',
            price: 4800,
            vat: 960,
            discountedPrice: 4230,
            quantity: 6,
            customerName: 'Adeline Stevens',
            customerStreet: '424 Fawn Drive',
            customerCity: 'Oak Forest',
            customerZIP: '60452',
            customerCountry: 'Greece',
            status: 'completed',
        },

        {
            id: 18,
            title: 'Srilanka',
            description: 'Sri Lanka is a beautiful island country in the Indian Ocean, about 32 kilometres off the south east coast of India.',
            coverImg: '/coverImages/srilanka.png',
            price: 1460,
            vat: 292,
            discountedPrice: 1250,
            quantity: 2,
            customerName: 'Bryan Hanson',
            customerStreet: '466 Longfellow St.',
            customerCity: 'Soddy Daisy',
            customerZIP: '37379',
            customerCountry: 'Malta',
            status: 'pending',
        },

        {
            id: 19,
            title: 'USA',
            description: 'Head on a tropical getaway to the islands of Hawaii to explore the dramatic history of Honolulu.',
            coverImg: '/coverImages/USA.png',
            price: 4800,
            vat: 960,
            discountedPrice: 3200,
            quantity: 4,
            customerName: 'Porter Aguirre',
            customerStreet: '5 Harrison St.',
            customerCity: 'Wenatchee',
            customerZIP: '98801',
            customerCountry: 'Luxembourg',
            status: 'completed',
        },

        {
            id: 20,
            title: 'India',
            description: 'The Golden Triangle is a great introduction to India, especially if time is limited.',
            coverImg: '/coverImages/India.png',
            price: 1300,
            vat: 260,
            discountedPrice: 1100,
            quantity: 5,
            customerName: 'Trinity Zamora',
            customerStreet: '9712 Kirkland Drive',
            customerCity: 'Raeford',
            customerZIP: '28376',
            customerCountry: 'Sweden',
            status: 'completed',
        },
    ]
}

export default getDataLaura